// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvjtsckzyfoqjavatvfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2anRzY2t6eWZvcWphdmF0dmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTI1MzQsImV4cCI6MjA2MDAyODUzNH0.7VkYgip_2ayvOzjqcF7tWEiGyZQpQcQf5IDLsJhge6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);